### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by bkazuo** [ShopBackBR/ProcessDataChallenge#1]
Bom dia,

Para as análises de perfil de gastos por categoria, percebi que existem diversas categorias para um mesmo produto. 
```
{
    "_id" : ObjectId("584c4753cd2f5b713808e334"),
...
    "categories" : [ 
        "Cosméticos", 
        "Cosméticos Profissionais", 
        "Líquidos", 
        "Gordura Localizada"
    ],
...
}
```
Por qual nível devo me orientar? Por exemplo, se existem 4 níveis, há alguma ordem de classificação (Cosméticos > Cosméticos Profissionais > Líquidos > Gordura Localizada)? Isso impactaria na análise de gastos por categoria caso fizesse um agrupamento, contando o produto 4 vezes.

**Comment by raphaelgiovanini** [comment]
Não há ordem de classificação.
